version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: express
    container_name: Express_server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
      driver: bridge
  web-root:
    driver: local
volumes:
  postgres:
