version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: express
    container_name: Express_server
    volumes:
      - /usr/src/app/node_modules   
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network


  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: posts
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

    networks:
      - app-network
networks:
  app-network:
      driver: bridge
 
volumes:
  postgres-data:
